rooms:
  1:
    name: "Entrée"
    cuboids:
      - "world, -814, 65, -74, -832, 78, -100"
      - "world, -811, 65, -74, -815, 71, -82"
      - "world, -831, 71, -93, -835, 78, -97"
    windows:
      - "world, -837, 73, -95"
      - "world, -835, 69, -77"
      - "world, -819, 69, -71"
      - "world, -813, 68, 97"
    center: "world, -822, 69, -82"
  2:
    name: "Balcon"
    cuboids:
      - "world, -807, 71, -105, -817, 78, -101"
      - "world, -803, 71, -102, -813, 78, -84"
      - "world, -802, 71, -93, -801, 78, -90"
      - "world, -787, 71, -103, -801, 78, -88"
    windows:
      - "world, -807, 73, -84"
      - "world, -785, 73, -95"
    center: "world, -807, 73, -95"