rooms:
  1:
    name: "Entrée"
    cuboids:
      - "world, -816, 65, -74, -831, 78, -99"
      - "world, -811, 65, -74, -815, 71, -81"
    windows:
      - "world, -837, 73, -95"
      - "world, -835, 69, -77"
      - "world, -819, 69, -71"
      - "world, -813, 68, 97"